name: zego_uikit_signal_plugin
description: ZegoUIKitSignalPlugin is a low-code plugin collection that provides the signal related function extensions for ZegoUIKit, which helps you to integarte features easier and faster.
version: 1.0.6
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_signal_plugin_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vibrate: ^1.3.0
  audioplayers: ^1.0.1
  statemachine: ^3.2.0
  flutter_screenutil: ^5.5.3+2
  permission_handler: ^10.0.2
  zego_zim: ^2.3.3
  zego_uikit: ^1.3.3
  zego_uikit_prebuilt_call: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'

flutter:
  assets:
    - assets/audio/callerRing.mp3
    - assets/audio/calleeRing.wav

    - assets/icons/invite_voice.png
    - assets/icons/invite_video.png
    - assets/icons/invite_reject.png
    - assets/icons/invite_background.png
    - assets/icons/toolbar_bottom_video.png
    - assets/icons/toolbar_bottom_voice.png
    - assets/icons/toolbar_bottom_decline.png
    - assets/icons/toolbar_bottom_cancel.png
    - assets/icons/toolbar_bottom_cancel.png
    - assets/icons/toolbar_top_switch_camera.png

    - assets/icons/2.0x/invite_voice.png
    - assets/icons/2.0x/invite_video.png
    - assets/icons/2.0x/invite_reject.png
    - assets/icons/2.0x/invite_background.png
    - assets/icons/2.0x/toolbar_bottom_video.png
    - assets/icons/2.0x/toolbar_bottom_voice.png
    - assets/icons/2.0x/toolbar_bottom_decline.png
    - assets/icons/2.0x/toolbar_bottom_cancel.png
    - assets/icons/2.0x/toolbar_bottom_cancel.png
    - assets/icons/2.0x/toolbar_top_switch_camera.png

    - assets/icons/3.0x/invite_voice.png
    - assets/icons/3.0x/invite_video.png
    - assets/icons/3.0x/invite_reject.png
    - assets/icons/3.0x/invite_background.png
    - assets/icons/3.0x/toolbar_bottom_video.png
    - assets/icons/3.0x/toolbar_bottom_voice.png
    - assets/icons/3.0x/toolbar_bottom_decline.png
    - assets/icons/3.0x/toolbar_bottom_cancel.png
    - assets/icons/3.0x/toolbar_bottom_cancel.png
    - assets/icons/3.0x/toolbar_top_switch_camera.png
