name: zego_uikit_signaling_plugin
description: ZegoUIKitSignalingPlugin is a low-code plugin collection that provides the signal related function extensions for ZegoUIKit, which helps you to integarte features easier and faster.
version: 2.1.1
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_signaling_plugin_flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_plugin_adapter: ^2.1.0
  zego_zim: 2.7.1
  zego_zpns: 2.3.2

  flutter_logs: ^2.1.10
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  plugin:
    platforms:
      android:
        package: com.zegocloud.uikit.flutter.signal_plugin.zego_uikit_signaling_plugin
        pluginClass: ZegoUikitSignalingPlugin
      ios:
        pluginClass: ZegoUikitSignalingPlugin
